In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.3'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [5]:
df.shape

(9704, 11)

In [6]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [7]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [8]:
condition = df['origin'] == 'Asia'
df.loc[condition, 'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [9]:
hp_med = df['horsepower'].median()
hp_mode = df['horsepower'].mode().iloc[0]

In [10]:
hp_med

np.float64(149.0)

In [11]:
hp_mode

np.float64(152.0)

In [12]:
df['horsepower'] = df['horsepower'].fillna(hp_mode)

In [13]:
hp_med = df['horsepower'].median()
hp_med

np.float64(152.0)

In [14]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [15]:
X = df.loc[condition][['vehicle_weight', 'model_year']].head(7)
X

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [16]:
XTX = X.to_numpy().T @ X.to_numpy()

In [17]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [18]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [19]:
w = np.linalg.inv(XTX) @ X.to_numpy().T @ y
w.sum()

np.float64(0.5187709081074016)